### ISSUE TITLE
Error with DataFrame in extracting timestamps from SPE file.

### ISSUE THREAD

**Issue by keatonb** [ccd-utexas/tsphot#110] opened 2015-03-31 18:09 UTC
When running the notebook code here: http://nbviewer.ipython.org/gist/ccd-admin/e3f5a7ce74f69a1f8ae5

I get the following error when evaluating Cell 4

```
/Users/keatonb/anaconda/lib/python2.7/site-packages/pandas/core/indexing.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)
```

**Comment by stharrold** [comment] 2015-03-31 19:01
duplicate of #107 
@keatonb the code executed correctly. warnings are different from errors.
to fix, make a temporary dataframe then use df.update (same as an inner join) instead of setting the value. let me know if you need help with the patch. thanks!

**Closed as completed by stharrold** 2015-03-31 19:01 UTC
Labels: bug, duplicate
